<html>
<head>
    <title>Create</title>
    <style>
        #code_snippet {
            width: 500px;
        }
    </style>
</head>
<body>
    <textarea id="code_snippet">// write your code here</textarea><br><br>
    <span>Time restriction: </span>
    <input id="time_restriction" type="text"/><br><br>
    <span>Views restriction: </span>
    <input id="views_restriction" type="text"/><br><br>
    <button id="send_snippet" type="submit" onclick="send()">Submit</button>
</body>
</html>